# Generated by Django 4.2.18 on 2025-01-16 05:47

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('customer_type', models.CharField(choices=[('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler'), ('Distributor', 'Distributor')], max_length=50, verbose_name='Customer Type')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact Information')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('billing_address', models.TextField(verbose_name='Billing Address')),
                ('shipping_address', models.TextField(verbose_name='Shipping Address')),
                ('credit_limit', models.FloatField(default=0.0, verbose_name='Credit Limit')),
                ('current_balance', models.FloatField(default=0.0, verbose_name='Current Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='Order Number')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50, verbose_name='Order Status')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Total Price')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Producer Name')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact Information')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('address', models.TextField(verbose_name='Physical Address')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='Registration Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Local Unit Location', null=True, srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('category', models.CharField(choices=[('FR', 'Fruits'), ('VG', 'Vegetables'), ('GR', 'Grains & Cereals'), ('PL', 'Pulses & Legumes'), ('SP', 'Spices & Herbs'), ('NT', 'Nuts & Seeds'), ('DF', 'Dairy & Animal Products'), ('FM', 'Fodder & Forage'), ('FL', 'Flowers & Ornamental Plants'), ('HR', 'Herbs & Medicinal Plants'), ('OT', 'Other')], default='FR', max_length=2)),
                ('description', models.TextField(verbose_name='Product Description')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Stock Keeping Unit (SKU)')),
                ('price', models.FloatField(verbose_name='Price')),
                ('cost_price', models.FloatField(verbose_name='Cost Price')),
                ('stock', models.IntegerField(verbose_name='Stock Quantity')),
                ('reorder_level', models.IntegerField(default=10, verbose_name='Reorder Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
                ('is_marketplace_created', models.BooleanField(default=False, verbose_name='Marketplace Created')),
                ('location', models.ForeignKey(blank=True, help_text='Location of the product', null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.city', verbose_name='Location')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.producer', verbose_name='Producer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_date', models.DateTimeField(auto_now_add=True, verbose_name='Moved Date')),
                ('is_pushed_to_marketplace', models.BooleanField(default=False, verbose_name='Is Stock moved to marketplace')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity Sold')),
                ('sale_price', models.FloatField(verbose_name='Sale Price')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sale Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50, verbose_name='Payment Status')),
                ('payment_due_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Due Date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='producer.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_price', models.FloatField(verbose_name='Listed Price')),
                ('listed_date', models.DateTimeField(auto_now_add=True, verbose_name='Listed Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('bid_end_date', models.DateTimeField(verbose_name='Bid End Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Marketplace Product',
                'verbose_name_plural': 'Marketplace Products',
            },
        ),
    ]
