# Generated by Django 4.2.18 on 2025-01-16 06:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producer',
            new_name='Supplier',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='producer',
            new_name='supplier',
        ),
    ]
